In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('/content/Titanic-Dataset.csv')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
## filling missing values :

df['Age'] = df['Age'].fillna(df['Age'].mean())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [ ]:
df["has_cabin"]  = df['Cabin'].notnull().astype(int)

In [ ]:
df = df.drop("Cabin", axis = 1)

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Gender         0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
has_cabin      0
dtype: int64

In [ ]:

new_df = df[["Survived"	,"Pclass","Age", "Gender", "has_cabin", "Fare", "Embarked"]]

In [ ]:

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
new_df["Gender"] = le.fit_transform(new_df["Gender"])
new_df['Embarked'] = le.fit_transform(new_df['Embarked'])

In [ ]:
new_df.head()

   Survived  Pclass   Age  Gender  has_cabin     Fare  Embarked
0         0       3  22.0       1          0   7.2500         2
1         1       1  38.0       0          1  71.2833         0
2         1       3  26.0       0          0   7.9250         2
3         1       1  35.0       0          1  53.1000         2
4         0       3  35.0       1          0   8.0500         2

In [ ]:
# one _ hot encding

new_df = pd.get_dummies(new_df, columns = ["Pclass"])
new_df= new_df.astype(int)

In [ ]:
new_df.head()

,Survived,Age,Gender,has_cabin,Fare,Embarked,Pclass_1,Pclass_2,Pclass_3
0,0,22,1,0,7,2,0,0,1
1,1,38,0,1,71,0,1,0,0
2,1,26,0,0,7,2,0,0,1
3,1,35,0,1,53,2,1,0,0
4,0,35,1,0,8,2,0,0,1

In [ ]:
##

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
new_df['Age'] = sc.fit_transform(df[['Age']])
new_df['Fare'] = sc.fit_transform(df[['Fare']])

In [ ]:
new_df.head()

,Survived,Age,Gender,has_cabin,Fare,Embarked,Pclass_1,Pclass_2,Pclass_3
0,0,-0.592481,1,0,-0.502445,2,0,0,1
1,1,0.638789,0,1,0.786845,0,1,0,0
2,1,-0.284663,0,0,-0.488854,2,0,0,1
3,1,0.407926,0,1,0.420730,2,1,0,0
4,0,0.407926,1,0,-0.486337,2,0,0,1

In [ ]:
## logistic regression

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
X = new_df.drop('Survived', axis = 1)
y = new_df['Survived']

In [ ]:
X_train , X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
model_log = LogisticRegression()
model_log.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred_log = model_log.predict(X_test)

In [ ]:
y_test

709    1
439    0
840    0
720    1
39     1
      ..
433    0
773    0
25     1
84     1
10     1
Name: Survived, Length: 179, dtype: int64

In [ ]:
y_pred_log

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1])

In [ ]:
model_log.score(X_test, y_test)

0.8044692737430168

In [ ]:
## modal evalution

In [ ]:
accuracy_score(y_test, y_pred_log)

0.8044692737430168

In [ ]:

confusion_matrix(y_test, y_pred_log)

array([[89, 16],
       [19, 55]])

In [ ]:
print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

           0       0.82      0.85      0.84       105
           1       0.77      0.74      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.80      0.80       179
weighted avg       0.80      0.80      0.80       179

In [ ]:
## Naive bayes

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
model_nb = GaussianNB()
model_nb.fit(X_train, y_train)

GaussianNB()

In [ ]:
model_nb.score(X_test, y_test)

0.7541899441340782

In [ ]:
pred_nb = model_nb.predict(X_test)

In [ ]:
accuracy_score(y_test, pred_nb)

0.7541899441340782

In [ ]:
print(classification_report(y_test, pred_nb))

              precision    recall  f1-score   support

           0       0.79      0.80      0.79       105
           1       0.71      0.69      0.70        74

    accuracy                           0.75       179
   macro avg       0.75      0.74      0.75       179
weighted avg       0.75      0.75      0.75       179

In [ ]:
confusion_matrix(y_test, pred_nb)

array([[84, 21],
       [23, 51]])

In [ ]:
###

In [ ]:
## SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
modal_svm = SVC(kernel = 'rbf')
modal_svm.fit(X_train, y_train)

SVC()

In [ ]:
pred_svm = modal_svm.predict(X_test)

In [ ]:
accuracy_score(y_test, pred_svm)

0.8044692737430168

In [ ]:
print(classification_report(y_test, pred_svm))

              precision    recall  f1-score   support

           0       0.79      0.90      0.84       105
           1       0.83      0.66      0.74        74

    accuracy                           0.80       179
   macro avg       0.81      0.78      0.79       179
weighted avg       0.81      0.80      0.80       179

In [ ]:
confusion_matrix(y_test, pred_svm)

array([[95, 10],
       [25, 49]])